[workspace]
default-members = ["fluorescence-scan"]
members = [ "fluorescence-scan", "models"]
resolver = "2"

[workspace.dependencies]
sea-orm = { version = "0.12.14", features = [
    "runtime-tokio-rustls",
    "sqlx-mysql",
] }
