[workspace]
default-members = ["fluorescence_scan"]
members = [ "fluorescence_scan", "models"]
resolver = "2"

[workspace.dependencies]
sea-orm = { version = "0.12.14", features = [
    "runtime-tokio-rustls",
    "sqlx-mysql",
] }
