apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: flourescence-scan-s3-secret
  namespace: graph
spec:
  encryptedData:
    access-key: AgCDep+tY9c2/nDCwBny47UrFLM6pPM7UUbqkS3tH9tpuYCtWtGI259YafjM65QslLDfQC2qkE3AL58K/bVdy+ppbb4b77ugz+oYEpS/eThP3wLBfCJxlXitVpSc2IXx4xRHGbXR8K1rdnmVWfbLbmcCi/2QqobCUMoqjWholjCKn+Tcle7SBtjs7SNad2kyXTAu2Ymgnei3zaf943uUIzoaXQh31o0i6f0xYCYhtD6Qdy33amk6ivR7OVIjsX3g7/1rlBV/tiQxZYwFPChW7AFTatpa39c1bjB5KMMfa9LcQq7AWuaCrG8DEXYKq/BI7nKoptrAzLGT0JSK5PmQ8N+9mCRbQffWCIhYN+X8GUclZHwhvUDkF2BQrpkL5XeS7fJkxzS/jHnEqnEKVMKbHZrhdu7OZq4741S+ptQhbVHKQ6V/rB1rwhcOlZk4G26nASPCWIDVLtX2409kqJWt6icd9SzDbrgpVQXJBYQwIuLt4rtwAmbP1Bxg5uZo5p+X+NNGO4kvT4opEGoz87mPa8naXkzv0kwTcs8yEku9Ie3Hknh3bcdtlne16b5SycODVtKVi7SDfMY2Wm9SSZwqm8zblsg5C9RG3uJ6quyfy9/ZsOxN+nzXbFab9R7gymyEXfEF5N+8SNiJUba5SkuXDGDjDcS0PAkQN9brCvFan17wV2X2dPVBelwoGVVWAk7gMlP8pH0Q
  template:
    metadata:
      creationTimestamp: null
      name: flourescence-scan-s3-secret
      namespace: graph
